---
title: "Assignment B3 Shiny App"
output: github_document
---

# Updated BC Liquor store application

This is an assignment B3 completed for UBC Stat 545B course. 

The basic BC Liquor store app demonstrated in class in upgraded with additional functionalities.

The app can be found at https://britttheuser.shinyapps.io/BCLAppUpdated/

## Here are the functionalities added during in-class demonstrations:
1. A slide bar to restrict price range of results
2. Radio buttons to select beverage type
3. A histogram displaying the alcohol content
4. A table of the restricted results


## Here are the functionalities added as part of the assignment B3:
1. A floating theme selector window that allows selection of themes for the entire app
2. A tab set panel that stores each resulting graph or table in a separate tab
3. A dropdown menu that allows users to choose whether to display results sorted by price
4. A 3rd tab in the result tab set that allows users to type in a brand to filter results
5. A BCL logo on the top right corner of the app
